print("Welcome to the Band Name Generator")
city = input("What is the name of the city you grew up in?\n").capitalize()
print(city)
pet = input("What is your pets name?\n").capitalize()
print(pet)
print("Your band name could be " + city + " " + pet)